### ISSUE TITLE
README.md - Quick Start section - More details on step 4

### ISSUE THREAD

**Issue by private-waveform** [kalouo/breadcrumbs#57]
Step 4 "Prepare your [config.hjson](https://github.com/kalouo/breadcrumbs/blob/master/config-template.hjson)" isn't very clear to me.

Can you provide more details on how to configure this and what each section in the config does?

**Comment by kalouo** [comment]
Hi. Thanks for dropping by. 

Could you please consult the wiki? It should have the information you need.

Will update the README to point people to the wiki.

**Comment by kalouo** [comment]
Let me know if any further questions

**Comment by kalouo** [comment]
https://github.com/kalouo/breadcrumbs/wiki
